"""empty message

Revision ID: 73959d0e18e8
Revises: 
Create Date: 2022-07-29 22:22:42.075166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73959d0e18e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('log_message', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.SmallInteger(), nullable=True),
    sa.Column('incorrect_answers', sa.SmallInteger(), nullable=True),
    sa.Column('remaining_time', sa.SmallInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('logs')
    # ### end Alembic commands ###
