"""empty message

Revision ID: fa658c193f3a
Revises: 
Create Date: 2024-09-13 01:27:44.685845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa658c193f3a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=80), nullable=True),
    sa.Column('log_message', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.SmallInteger(), nullable=True),
    sa.Column('incorrect_answers', sa.SmallInteger(), nullable=True),
    sa.Column('remaining_time', sa.SmallInteger(), nullable=True),
    sa.Column('user_name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('logs')
    # ### end Alembic commands ###
